print("==========INPUT==========")
nama = input("Nama Lengkap: ")
ttl = input("TTL: ")
alamat = input("Alamat: ")
nomorhp = input("No.Hp: ")
programstudi = input("Program Study: ")
hobi = input("Hobi: ")

print("==========OUTPUT==========")
print("Biodata Diri")
print("Nama: ", nama)
print("TTL: ",ttl)
print("Alamat: ",alamat)
print("No.Hp: ",nomorhp)
print("Program Study: ",programstudi)
print("Hobi: ",hobi)